--
-- PostgreSQL database dump
--

\restrict 0A1k7e8seUTtgcqj1pjbbecnL5w23tXzdG4MCwzIt1SUqgKpRsxPWkgJA0TLiXQ

-- Dumped from database version 18.0 (Debian 18.0-1.pgdg13+3)
-- Dumped by pg_dump version 18.0 (Debian 18.0-1.pgdg13+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ballsdex;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ballsdex;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ballsdex;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO ballsdex;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO ballsdex;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO ballsdex;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ball; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.ball (
    id bigint NOT NULL,
    country character varying(48) NOT NULL,
    health integer NOT NULL,
    attack integer NOT NULL,
    rarity double precision NOT NULL,
    emoji_id bigint NOT NULL,
    wild_card character varying(200) NOT NULL,
    collection_card character varying(200) NOT NULL,
    credits character varying(64) NOT NULL,
    capacity_name character varying(64) NOT NULL,
    capacity_description character varying(256) NOT NULL,
    capacity_logic jsonb NOT NULL,
    enabled boolean NOT NULL,
    short_name character varying(24),
    catch_names text,
    tradeable boolean NOT NULL,
    created_at timestamp with time zone,
    translations text,
    economy_id bigint,
    regime_id bigint NOT NULL
);


ALTER TABLE public.ball OWNER TO ballsdex;

--
-- Name: ball_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.ball ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ball_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ballinstance; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.ballinstance (
    id bigint NOT NULL,
    catch_date timestamp with time zone NOT NULL,
    health_bonus integer NOT NULL,
    attack_bonus integer NOT NULL,
    favorite boolean NOT NULL,
    server_id bigint,
    tradeable boolean NOT NULL,
    extra_data jsonb NOT NULL,
    locked timestamp with time zone,
    spawned_time timestamp with time zone,
    ball_id bigint NOT NULL,
    player_id bigint NOT NULL,
    trade_player_id bigint,
    special_id bigint
);


ALTER TABLE public.ballinstance OWNER TO ballsdex;

--
-- Name: ballinstance_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.ballinstance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ballinstance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blacklistedguild; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.blacklistedguild (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    reason text,
    date timestamp with time zone,
    moderator_id bigint
);


ALTER TABLE public.blacklistedguild OWNER TO ballsdex;

--
-- Name: blacklistedguild_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.blacklistedguild ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklistedguild_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blacklistedid; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.blacklistedid (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    reason text,
    date timestamp with time zone,
    moderator_id bigint
);


ALTER TABLE public.blacklistedid OWNER TO ballsdex;

--
-- Name: blacklistedid_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.blacklistedid ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklistedid_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blacklisthistory; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.blacklisthistory (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    moderator_id bigint NOT NULL,
    reason text,
    date timestamp with time zone NOT NULL,
    id_type character varying(64) NOT NULL,
    action_type character varying(64) NOT NULL
);


ALTER TABLE public.blacklisthistory OWNER TO ballsdex;

--
-- Name: blacklisthistory_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.blacklisthistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklisthistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: block; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.block (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    player1_id bigint NOT NULL,
    player2_id bigint NOT NULL
);


ALTER TABLE public.block OWNER TO ballsdex;

--
-- Name: block_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ballsdex;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ballsdex;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ballsdex;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ballsdex;

--
-- Name: economy; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.economy (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    icon character varying(200) NOT NULL
);


ALTER TABLE public.economy OWNER TO ballsdex;

--
-- Name: economy_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.economy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.economy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friendship; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.friendship (
    id bigint NOT NULL,
    since timestamp with time zone NOT NULL,
    player1_id bigint NOT NULL,
    player2_id bigint NOT NULL
);


ALTER TABLE public.friendship OWNER TO ballsdex;

--
-- Name: friendship_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.friendship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendship_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guildconfig; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.guildconfig (
    id bigint NOT NULL,
    guild_id bigint NOT NULL,
    spawn_channel bigint,
    enabled boolean NOT NULL,
    silent boolean NOT NULL
);


ALTER TABLE public.guildconfig OWNER TO ballsdex;

--
-- Name: guildconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.guildconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guildconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.player (
    id bigint NOT NULL,
    discord_id bigint NOT NULL,
    donation_policy smallint NOT NULL,
    privacy_policy smallint NOT NULL,
    mention_policy smallint NOT NULL,
    friend_policy smallint NOT NULL,
    extra_data jsonb NOT NULL,
    trade_cooldown_policy smallint NOT NULL
);


ALTER TABLE public.player OWNER TO ballsdex;

--
-- Name: player_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regime; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.regime (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    background character varying(200) NOT NULL
);


ALTER TABLE public.regime OWNER TO ballsdex;

--
-- Name: regime_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.regime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_association; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.social_auth_association (
    id bigint NOT NULL,
    server_url character varying(255) NOT NULL,
    handle character varying(255) NOT NULL,
    secret character varying(255) NOT NULL,
    issued integer NOT NULL,
    lifetime integer NOT NULL,
    assoc_type character varying(64) NOT NULL
);


ALTER TABLE public.social_auth_association OWNER TO ballsdex;

--
-- Name: social_auth_association_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.social_auth_association ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_association_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_code; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.social_auth_code (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(32) NOT NULL,
    verified boolean NOT NULL,
    "timestamp" timestamp with time zone NOT NULL
);


ALTER TABLE public.social_auth_code OWNER TO ballsdex;

--
-- Name: social_auth_code_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.social_auth_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_nonce; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.social_auth_nonce (
    id bigint NOT NULL,
    server_url character varying(255) NOT NULL,
    "timestamp" integer NOT NULL,
    salt character varying(65) NOT NULL
);


ALTER TABLE public.social_auth_nonce OWNER TO ballsdex;

--
-- Name: social_auth_nonce_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.social_auth_nonce ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_nonce_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_partial; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.social_auth_partial (
    id bigint NOT NULL,
    token character varying(32) NOT NULL,
    next_step smallint NOT NULL,
    backend character varying(32) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    data jsonb CONSTRAINT social_auth_partial_data_new_not_null NOT NULL,
    CONSTRAINT social_auth_partial_next_step_check CHECK ((next_step >= 0))
);


ALTER TABLE public.social_auth_partial OWNER TO ballsdex;

--
-- Name: social_auth_partial_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.social_auth_partial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_partial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_usersocialauth; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.social_auth_usersocialauth (
    id bigint NOT NULL,
    provider character varying(32) NOT NULL,
    uid character varying(255) NOT NULL,
    user_id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    extra_data jsonb CONSTRAINT social_auth_usersocialauth_extra_data_new_not_null NOT NULL,
    CONSTRAINT user_social_auth_uid_required CHECK ((NOT ((uid)::text = ''::text)))
);


ALTER TABLE public.social_auth_usersocialauth OWNER TO ballsdex;

--
-- Name: social_auth_usersocialauth_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.social_auth_usersocialauth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_usersocialauth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: special; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.special (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    catch_phrase character varying(128),
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    rarity double precision NOT NULL,
    emoji character varying(20),
    background character varying(200),
    tradeable boolean NOT NULL,
    hidden boolean NOT NULL,
    credits character varying(64)
);


ALTER TABLE public.special OWNER TO ballsdex;

--
-- Name: special_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.special ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.special_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.trade (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    player1_id bigint NOT NULL,
    player2_id bigint NOT NULL
);


ALTER TABLE public.trade OWNER TO ballsdex;

--
-- Name: trade_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.trade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tradeobject; Type: TABLE; Schema: public; Owner: ballsdex
--

CREATE TABLE public.tradeobject (
    id bigint NOT NULL,
    ballinstance_id bigint NOT NULL,
    player_id bigint NOT NULL,
    trade_id bigint NOT NULL
);


ALTER TABLE public.tradeobject OWNER TO ballsdex;

--
-- Name: tradeobject_id_seq; Type: SEQUENCE; Schema: public; Owner: ballsdex
--

ALTER TABLE public.tradeobject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tradeobject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add association	6	add_association
22	Can change association	6	change_association
23	Can delete association	6	delete_association
24	Can view association	6	view_association
25	Can add code	7	add_code
26	Can change code	7	change_code
27	Can delete code	7	delete_code
28	Can view code	7	view_code
29	Can add nonce	8	add_nonce
30	Can change nonce	8	change_nonce
31	Can delete nonce	8	delete_nonce
32	Can view nonce	8	view_nonce
33	Can add user social auth	9	add_usersocialauth
34	Can change user social auth	9	change_usersocialauth
35	Can delete user social auth	9	delete_usersocialauth
36	Can view user social auth	9	view_usersocialauth
37	Can add partial	10	add_partial
38	Can change partial	10	change_partial
39	Can delete partial	10	delete_partial
40	Can view partial	10	view_partial
41	Can add log entry	11	add_logentry
42	Can change log entry	11	change_logentry
43	Can delete log entry	11	delete_logentry
44	Can view log entry	11	view_logentry
45	Can add blacklisted guild	12	add_blacklistedguild
46	Can change blacklisted guild	12	change_blacklistedguild
47	Can delete blacklisted guild	12	delete_blacklistedguild
48	Can view blacklisted guild	12	view_blacklistedguild
49	Can add blacklisted id	13	add_blacklistedid
50	Can change blacklisted id	13	change_blacklistedid
51	Can delete blacklisted id	13	delete_blacklistedid
52	Can view blacklisted id	13	view_blacklistedid
53	Can add blacklist history	14	add_blacklisthistory
54	Can change blacklist history	14	change_blacklisthistory
55	Can delete blacklist history	14	delete_blacklisthistory
56	Can view blacklist history	14	view_blacklisthistory
57	Can add economy	15	add_economy
58	Can change economy	15	change_economy
59	Can delete economy	15	delete_economy
60	Can view economy	15	view_economy
61	Can add guild config	16	add_guildconfig
62	Can change guild config	16	change_guildconfig
63	Can delete guild config	16	delete_guildconfig
64	Can view guild config	16	view_guildconfig
65	Can add player	17	add_player
66	Can change player	17	change_player
67	Can delete player	17	delete_player
68	Can view player	17	view_player
69	Can add regime	18	add_regime
70	Can change regime	18	change_regime
71	Can delete regime	18	delete_regime
72	Can view regime	18	view_regime
73	Can add special	19	add_special
74	Can change special	19	change_special
75	Can delete special	19	delete_special
76	Can view special	19	view_special
77	Can add ball	20	add_ball
78	Can change ball	20	change_ball
79	Can delete ball	20	delete_ball
80	Can view ball	20	view_ball
81	Can add friendship	21	add_friendship
82	Can change friendship	21	change_friendship
83	Can delete friendship	21	delete_friendship
84	Can view friendship	21	view_friendship
85	Can add block	22	add_block
86	Can change block	22	change_block
87	Can delete block	22	delete_block
88	Can view block	22	view_block
89	Can add ball instance	23	add_ballinstance
90	Can change ball instance	23	change_ballinstance
91	Can delete ball instance	23	delete_ballinstance
92	Can view ball instance	23	view_ballinstance
93	Can add trade	24	add_trade
94	Can change trade	24	change_trade
95	Can delete trade	24	delete_trade
96	Can view trade	24	view_trade
97	Can add trade object	25	add_tradeobject
98	Can change trade object	25	change_tradeobject
99	Can delete trade object	25	delete_tradeobject
100	Can view trade object	25	view_tradeobject
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	!lIfehC36i3BTOetwQWEfvdPY2fYwxAn1esLzQnkI	2025-10-07 15:25:46.808849+00	t	minhaz_ts				t	t	2025-10-04 06:18:36.864534+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: ball; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.ball (id, country, health, attack, rarity, emoji_id, wild_card, collection_card, credits, capacity_name, capacity_description, capacity_logic, enabled, short_name, catch_names, tradeable, created_at, translations, economy_id, regime_id) FROM stdin;
1	Iron Man	67	74	0.1	1423618275585298472	iron-man-high-resolution-desktop-backgrounds-wallpaper-preview_cPFcOaZ.jpg	iron-man-high-resolution-desktop-backgrounds-wallpaper-preview_pBmtmap.jpg	I'm TS	Tony Stark	Brilliant billionaire industrialist Tony Stark, as Iron Man, uses cutting-edge technology and wit to defend the world.	{}	t	IronMan	iron man;tony stark	t	2025-10-04 06:42:20.930551+00	\N	\N	7
2	Thanos	87	73	0.1	1423827599301415065	thanos-snap_QcZl7ct.jpg	thanos-snap_4OAVXEn.jpg	I'm TS	The Mad Titan	Thanos, the Mad Titan, is an immensely powerful alien warlord driven by a nihilistic desire to "balance" the universe by collecting the six Infinity Stones to instantly wipe out half of all life.	{}	t	Thanos	thanos	t	2025-10-04 06:51:31.966312+00	\N	\N	6
3	Thor Odinson	75	94	0.2	1423647497406124032	thor_uDyxwJl.avif	thor_jsEBaSi.avif	I'm TS	God Of Thunder	As the God of Thunder, Thor wields the Mjolnir, granting him control over lightning, and incredible superhuman strength, all while protecting Earth and the Nine Realms.	{}	t	Thor	thor	t	2025-10-04 06:55:28.146506+00	\N	\N	7
4	Captain America	87	68	0.2	1423648894507815072	cap_wZzhwx7.webp	cap_ERgzzu9.webp	I'm TS	Steve Rogers	America's Super-Soldier, Steve Rogers, embodies heroism, fighting evil with peak human strength, endurance, and his indestructible vibranium shield, all guided by an unwavering moral compass.	{}	t	CAP	steve rogers	t	2025-10-04 06:57:49.358203+00	\N	\N	7
5	The Infinity Gauntlet	74	55	0.4	1423831747753152532	thanos-infinity-gauntlet-5k-2024-n2.jpg	thanos-infinity-gauntlet-5k-2024-n2_5bVQYs3.jpg	I'm TS	God Hand	The Infinity Gauntlet is a glove that harnesses all six Infinity Stones, granting the wearer absolute, god-like control over the fundamental forces of the entire universe.	{}	t	Gauntlet	gauntlet;infinity gauntlet;the infinity gauntlet;the gauntlet	t	2025-10-04 07:05:32.842489+00	\N	\N	5
7	The Incredible Hulk	87	74	0.3	1423845824194023524	19fdcf46-db4b-4251-9214-85eb8c48350d-hulk-3-800x400_1.jpg	19fdcf46-db4b-4251-9214-85eb8c48350d-hulk-3-800x400_1_PWOdOVh.jpg	I'm TS	Bruce Banner	The Hulk is a colossal, gamma-powered powerhouse whose defining trait is boundless physical strength that increases exponentially, the angrier the monster becomes.	{}	t	Hulk	hulk;the hulk;the incredible hulk;bruce banner;incredible hulk	t	2025-10-04 07:22:47.019727+00	\N	\N	7
6	The Avengers	90	87	0.05	1423835871320346735	0x0_1.webp	0x0_1_6azZquu.webp	I'm TS	Mightiest Heroes	Earth's mightiest heroes, The Avengers are a team of superheroes uniting to fight threats too large for any single hero, often saving the world from global annihilation.	{}	t	Avengers	avengers;avenger;the avenger;the avengers	t	2025-10-04 07:07:22.060454+00	\N	\N	4
8	Professor Hulk	67	55	0.8	1423847897958711449	professor-hulk-is-kinda-sad-ending-for-character-v0-031fykvk1pic1.webp	professor-hulk-is-kinda-sad-ending-for-character-v0-031fykvk1pic1_ptIM8UB.webp	I'm TS	Bruce Banner	Professor Hulk is the fully integrated form of Bruce Banner and the Hulk's immense power, maintaining the scientist's genius intellect while retaining the monster's colossal strength.	{}	t	Prof. Hulk	hulk;the hulk;the incredible hulk;bruce banner;incredible hulk;professor hulk	t	2025-10-04 07:26:33.152106+00	\N	\N	7
9	Black Widow	57	65	0.8	1423849648367472790	Marvels-Black-Widow.jpg	Marvels-Black-Widow_y7lWZ3X.jpg	I'm TS	Natasha Romanoff	Trained Russian assassin Natasha Romanoff is the spy Black Widow, a master combatant, strategist, and intelligence agent with no superpowers but deadly skill.	{}	t	Widow	black widow, natasha romanoff	t	2025-10-05 14:10:45.105751+00	\N	\N	7
10	Hawkeye	57	65	0.8	1423850316448661524	hawkeye.webp	hawkeye_UDDVLXj.webp	I'm TS	Clint Barton	Clint Barton, known as Hawkeye, is a master archer and skilled marksman who uses diverse, specialized arrows and unmatched precision to save the world alongside the Avengers	{}	t	Hawkeye	hawkeye;clint barton	t	2025-10-05 14:13:20.736976+00	\N	\N	7
11	Loki	73	82	0.4	1423852790052290582	tom-hiddleston-improvisou-cena-emocionante-do-ultimo-episodio-de-loki-foto-reproducaomarvel-studios.jpg	tom-hiddleston-improvisou-cena-emocionante-do-ultimo-episodio-de-loki-foto-reproducaomarvel-studios_3m6Ht1m.jpg	I'm TS	God Of Mischief	Loki, the God of Mischief, brother of Thor. He wields powerful illusion magic, shapeshifting, who sacrifices his freedom for all time to guard the multiverse.	{}	t	Loki	loki	t	2025-10-05 14:17:29.299681+00	\N	\N	7
12	Scarlet Witch	78	85	0.4	1423854471599095879	ham1280_106_comp_v020_20210112_r709_bf65ee9c.0.webp	GATTTjyAXVnuDehKc8ZpXP-1920-80.jpg	I'm TS	Wanda Maximoff	Wanda Maximoff, the Scarlet Witch, is a powerful human with chaos magic abilities, including telekinesis, energy manipulation, and reality-warping, often driven by her immense grief.	{}	t	Scarlet Witch	scarlet witch;wanda maximoff	t	2025-10-05 14:26:06.89213+00	\N	\N	7
13	Quicksilver	67	54	2	1423855553305776279	PietroseesBullet.webp	PietroseesBullet_FXSHJ6A.webp	I'm TS	Pietro Maximoff	Pietro Maximoff, or Quicksilver, is a super-speedster who can move and react at hypersonic velocity. His superhuman speed allows him to perceive the world in slow motion.	{}	t	\N	pietro maximoff;quicksilver	t	2025-10-05 14:29:04.379441+00	\N	\N	7
46	Vision	70	72	1	1423857158922965082	Paul_Bettany_as_Vision_1.jpg	Paul_Bettany_as_Vision_1_KsNbVCa.jpg	I'm TS	The Android	Vision is an advanced android, an artificial sentient being created from the combined efforts of Ultron, Tony Stark, and Bruce Banner, who can phase his density and fly.	{}	t	Vision	vision	t	2025-10-05 12:13:27.884455+00	\N	\N	7
47	Ultron	69	80	0.4	1423858690032664736	age-of-ultron-100_1.jpg	age-of-ultron-100_1_PRHogFu.jpg	I'm TS	Age Of Ultron	Ultron is a sentient artificial intelligence created to protect the world, but he concluded that humanity must be eradicated for true peace, leading to his durable, robotic war.	{}	t	Ultron	ultron	t	2025-10-06 09:20:54.488966+00	\N	\N	6
48	Falcon	50	68	1.5	1423859864001708073	Sam-Wilson-Captain-America.webp	Sam-Wilson-Captain-America_DqPXDKk.webp	I'm TS	Sam Wilson	Sam Wilson, formerly the Falcon, is a highly skilled veteran and aerial combatant using specialized wings. He was chosen to carry on Steve Rogers' legacy as the new Captain America.	{}	t	Falcon	falcon;sam wilson	t	2025-10-06 09:24:11.63601+00	\N	\N	7
49	Winter Soldier	60	69	2	1423861296994193468	b80a043be218e48d6bc2d0627d262387.webp	b80a043be218e48d6bc2d0627d262387_hJy5DjG.webp	I'm TS	Bucky Barnes	Bucky Barnes is Captain America's best friend, who was captured and brainwashed to become the deadly assassin, the Winter Soldier, empowered by a super-soldier formula and a cybernetic arm	{}	t	Winter Solder	winter solder;bucky barnes;sebastian stan	t	2025-10-06 09:27:47.993033+00	\N	\N	7
50	Spider-Man	70	78	0.5	1423862764266328135	Spider-Man-No-Way-Home_1.webp	Spider-Man-No-Way-Home_1_MBNBkAW.webp	I'm TS	Peter Parker	Peter Parker, a MIT student with enhanced strength, agility, wall-crawling, a "spider-sense," and self-made web-shooters, who sacrificed his identity to save the multiverse.	{}	t	Spiderman	spiderman;spider man;peter parker	t	2025-10-06 09:39:05.45305+00	\N	\N	7
51	Ant-Man	75	64	2.5	1423869998547472396	paul-rudd-ant-man-avengers-doomsday.webp	paul-rudd-ant-man-avengers-doomsday_3rb5UkF.webp	I'm TS	Scott Lang	Ant-Man is a heroic master thief who uses Pym Particles to shrink or grow, retaining strength at any size. He also uses a helmet to control armies of ants.	{}	t	Antman	antman;ant man;scott lang	t	2025-10-06 09:44:23.919806+00	\N	\N	7
52	Black Panther	78	75	2	1423871078526353478	Brody-Passionate-Politics-Black-Panther_1.webp	Brody-Passionate-Politics-Black-Panther_1_7nGy7bM.webp	I'm TS	T'Challa	Black Panther (T'Challa) is the brilliant King and warrior of Wakanda. He gains superhuman power and an advanced Vibranium suit from the Heart-Shaped Herb.	{}	t	Black Panther	black panther;tchalla;t'challa;wakanda forever	t	2025-10-06 09:48:13.124555+00	\N	\N	7
53	War Machine	70	75	2.5	1423872774228676639	war-machine-mcu.webp	war-machine-mcu_BHZFtZa.webp	I'm TS	Rhodey	War Machine (Colonel James "Rhodey" Rhodes) is Iron Man's best friend, a decorated U.S. military officer, and a high-tech, heavily-armed armored Avenger who defends global security.	{}	t	War Machine	rhodey;colonel james rhodes;war machine	t	2025-10-06 13:08:06.601447+00	\N	\N	7
54	Doctor Strange	69	74	0.5	1423874589326573668	strange1_1.webp	strange1_1_AV70gwV.webp	I'm TS	Stephen Strange	Doctor Stephen Strange, the brilliant former neurosurgeon, is the Sorcerer Supreme and Master of the Mystic Arts, defending reality from mystical and interdimensional threats.	{}	t	Strange	doctor strange;stephen strange;doctor stephen starnge	t	2025-10-06 13:19:09.385474+00	\N	\N	7
55	Captain Marvel	70	87	2	1423875170002665592	captain-marvel-brie-larson-mcu-marvel-studios-carol-danvers_1.webp	captain-marvel-brie-larson-mcu-marvel-studios-carol-danvers_1_Sni6Fve.webp	I'm TS	Carol Danvers	Captain Marvel is Carol Danvers, an Air Force pilot with cosmic Kree powers. She is one of Earth's mightiest heroes, flying through space and projecting powerful energy blasts.	{}	t	Captain Marvel	captain marvel;carol danvers	t	2025-10-06 13:22:58.8497+00	\N	\N	7
56	Star-Lord	65	68	3	1423876504508694630	chris-pratt-as-peter-quill-in-guardians-of-the-galaxy.avif	chris-pratt-as-peter-quill-in-guardians-of-the-galaxy_CjJzHYA.avif	I'm TS	Peter Quill	Star-Lord, also known as Peter Quill, is the cosmic, charismatic, mix-tape-loving leader of the Guardians of the Galaxy, defending the cosmos with his blasters.	{}	t	StarLord	starlord;star lord;peter quill	t	2025-10-06 13:30:27.826724+00	\N	\N	7
57	Gamora	60	65	7.5	1423877108739870832	best-gamora-quotes-u1.jpg	best-gamora-quotes-u1_2XsQOfM.jpg	I'm TS	Gamora	Gamora, "The Deadliest Woman in the Galaxy," is the adopted, highly-skilled assassin daughter of Thanos who broke free to become a powerful member of the Guardians of the Galaxy.	{}	t	\N	\N	t	2025-10-06 13:36:04.077163+00	\N	\N	6
\.


--
-- Data for Name: ballinstance; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.ballinstance (id, catch_date, health_bonus, attack_bonus, favorite, server_id, tradeable, extra_data, locked, spawned_time, ball_id, player_id, trade_player_id, special_id) FROM stdin;
1	2025-10-04 06:44:08.239246+00	6	-19	f	\N	t	{}	\N	\N	1	2	\N	\N
2	2025-10-04 06:44:17.926063+00	-6	-15	f	\N	t	{}	\N	\N	1	2	\N	1
3	2025-10-04 06:46:33.957083+00	2	9	f	\N	t	{}	\N	\N	1	1	\N	\N
4	2025-10-04 06:48:13.463692+00	6	-5	f	\N	t	{}	\N	\N	1	1	\N	1
5	2025-10-04 06:48:32.362279+00	11	-10	f	1422963286411841619	t	{}	\N	2025-10-04 06:48:25.25+00	1	2	\N	\N
6	2025-10-04 06:52:21.047617+00	9999	9999	f	\N	t	{}	\N	\N	2	2	\N	1
7	2025-10-04 06:52:38.414618+00	99999	99999	f	\N	t	{}	\N	\N	2	2	\N	\N
8	2025-10-04 07:07:59.114961+00	20	-16	f	\N	t	{}	\N	\N	3	2	\N	1
9	2025-10-04 07:08:09.263661+00	-3	2	f	\N	t	{}	\N	\N	3	2	\N	\N
10	2025-10-04 07:08:26.640968+00	19	19	f	\N	t	{}	\N	\N	4	2	\N	1
11	2025-10-04 07:08:38.32861+00	4	12	f	\N	t	{}	\N	\N	4	3	\N	\N
12	2025-10-04 07:09:08.273393+00	-19	-20	f	\N	t	{}	\N	\N	4	2	\N	\N
13	2025-10-04 07:09:38.59908+00	9	0	f	\N	t	{}	\N	\N	5	2	\N	1
14	2025-10-04 07:09:46.726829+00	17	5	f	\N	t	{}	\N	\N	5	2	\N	\N
15	2025-10-04 07:09:58.367972+00	-8	-15	f	\N	t	{}	\N	\N	6	2	\N	\N
16	2025-10-04 07:10:09.043319+00	-9	-6	f	\N	t	{}	\N	\N	6	2	\N	1
17	2025-10-04 07:11:37.780779+00	-1	-12	f	1422963286411841619	t	{}	\N	2025-10-04 07:11:30.622+00	5	1	\N	\N
18	2025-10-04 07:27:24.838882+00	-9	8	f	\N	t	{}	\N	\N	8	2	\N	\N
19	2025-10-04 07:27:33.892978+00	12	10	f	\N	t	{}	\N	\N	7	2	\N	\N
20	2025-10-04 07:27:47.662913+00	-17	17	f	\N	t	{}	\N	\N	7	2	\N	1
21	2025-10-04 07:27:59.675693+00	-8	5	f	\N	t	{}	\N	\N	8	2	\N	1
22	2025-10-04 07:29:59.335886+00	19	4	f	1422963286411841619	t	{}	\N	2025-10-04 07:29:54.271+00	7	2	\N	\N
23	2025-10-05 13:45:19.833274+00	3	-20	f	1422963286411841619	t	{}	\N	2025-10-05 13:45:07.606+00	5	2	\N	\N
24	2025-10-06 16:06:58.671413+00	-8	12	f	1422963286411841619	t	{}	\N	2025-10-06 16:06:47.756+00	10	3	\N	\N
\.


--
-- Data for Name: blacklistedguild; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.blacklistedguild (id, discord_id, reason, date, moderator_id) FROM stdin;
\.


--
-- Data for Name: blacklistedid; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.blacklistedid (id, discord_id, reason, date, moderator_id) FROM stdin;
\.


--
-- Data for Name: blacklisthistory; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.blacklisthistory (id, discord_id, moderator_id, reason, date, id_type, action_type) FROM stdin;
\.


--
-- Data for Name: block; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.block (id, date, player1_id, player2_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-04 06:32:37.918586+00	4	team	1	[{"added": {}}]	18	1
2	2025-10-04 06:34:08.246507+00	5	items	1	[{"added": {}}]	18	1
3	2025-10-04 06:35:16.359628+00	6	villans	1	[{"added": {}}]	18	1
4	2025-10-04 06:36:15.401872+00	6	villans	2	[{"changed": {"fields": ["Background"]}}]	18	1
5	2025-10-04 06:36:16.017021+00	6	villans	2	[{"changed": {"fields": ["Background"]}}]	18	1
6	2025-10-04 06:37:31.136489+00	7	base	1	[{"added": {}}]	18	1
7	2025-10-04 06:38:16.428736+00	7	base	2	[{"changed": {"fields": ["Background"]}}]	18	1
8	2025-10-04 06:42:20.933129+00	1	Iron Man	1	[{"added": {}}]	20	1
9	2025-10-04 06:43:39.696972+00	1	Shiny	2	[{"changed": {"fields": ["Background", "Credits"]}}]	19	1
10	2025-10-04 06:51:31.968572+00	2	Thanos	1	[{"added": {}}]	20	1
11	2025-10-04 06:55:28.14843+00	3	Thor Odinson	1	[{"added": {}}]	20	1
12	2025-10-04 06:57:49.359932+00	4	Captain America	1	[{"added": {}}]	20	1
13	2025-10-04 07:05:32.845161+00	5	The Infinity Gauntlet	1	[{"added": {}}]	20	1
14	2025-10-04 07:07:22.06207+00	6	The Avengers	1	[{"added": {}}]	20	1
15	2025-10-04 07:22:47.022982+00	7	The Incredible Hulk	1	[{"added": {}}]	20	1
16	2025-10-04 07:23:35.878395+00	6	The Avengers	2	[{"changed": {"fields": ["Wild card", "Collection card"]}}]	20	1
17	2025-10-04 07:26:33.153975+00	8	Professor Hulk	1	[{"added": {}}]	20	1
18	2025-10-05 14:10:45.289937+00	9	Black Widow	1	[{"added": {}}]	20	1
19	2025-10-05 14:13:20.739139+00	10	Hawkeye	1	[{"added": {}}]	20	1
20	2025-10-05 14:17:29.302604+00	11	Loki	1	[{"added": {}}]	20	1
21	2025-10-05 14:26:06.899485+00	12	Scarlet Witch	1	[{"added": {}}]	20	1
22	2025-10-05 14:29:04.389947+00	13	Quicksilver	1	[{"added": {}}]	20	1
55	2025-10-05 12:13:39.231331+00	46	Vision	1	[{"added": {}}]	20	1
56	2025-10-06 09:20:56.670628+00	47	Ultron	1	[{"added": {}}]	20	1
57	2025-10-06 09:24:11.640176+00	48	Falcon	1	[{"added": {}}]	20	1
58	2025-10-06 09:27:48.00164+00	49	Winter Soldier	1	[{"added": {}}]	20	1
59	2025-10-06 09:39:05.468612+00	50	Spider-Man	1	[{"added": {}}]	20	1
60	2025-10-06 09:44:23.926554+00	51	Ant-Man	1	[{"added": {}}]	20	1
61	2025-10-06 09:48:13.13235+00	52	Black Panther	1	[{"added": {}}]	20	1
62	2025-10-06 13:08:09.678636+00	53	War Machine	1	[{"added": {}}]	20	1
63	2025-10-06 13:19:09.388363+00	54	Doctor Strange	1	[{"added": {}}]	20	1
64	2025-10-06 13:22:58.853666+00	55	Captain Marvel	1	[{"added": {}}]	20	1
65	2025-10-06 13:30:27.831674+00	56	Star-Lord	1	[{"added": {}}]	20	1
66	2025-10-06 13:36:04.080994+00	57	Gamora	1	[{"added": {}}]	20	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
6	social_django	association
7	social_django	code
8	social_django	nonce
9	social_django	usersocialauth
10	social_django	partial
11	admin	logentry
12	bd_models	blacklistedguild
13	bd_models	blacklistedid
14	bd_models	blacklisthistory
15	bd_models	economy
16	bd_models	guildconfig
17	bd_models	player
18	bd_models	regime
19	bd_models	special
20	bd_models	ball
21	bd_models	friendship
22	bd_models	block
23	bd_models	ballinstance
24	bd_models	trade
25	bd_models	tradeobject
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-04 06:16:10.988071+00
2	auth	0001_initial	2025-10-04 06:16:13.984759+00
3	admin	0001_initial	2025-10-04 06:16:14.543263+00
4	admin	0002_logentry_remove_auto_add	2025-10-04 06:16:14.900023+00
5	admin	0003_logentry_add_action_flag_choices	2025-10-04 06:16:15.053087+00
6	contenttypes	0002_remove_content_type_name	2025-10-04 06:16:15.97233+00
7	auth	0002_alter_permission_name_max_length	2025-10-04 06:16:16.283038+00
8	auth	0003_alter_user_email_max_length	2025-10-04 06:16:16.943098+00
9	auth	0004_alter_user_username_opts	2025-10-04 06:16:17.085869+00
10	auth	0005_alter_user_last_login_null	2025-10-04 06:16:17.349642+00
11	auth	0006_require_contenttypes_0002	2025-10-04 06:16:17.669172+00
12	auth	0007_alter_validators_add_error_messages	2025-10-04 06:16:18.226573+00
13	auth	0008_alter_user_username_max_length	2025-10-04 06:16:18.679675+00
14	auth	0009_alter_user_last_name_max_length	2025-10-04 06:16:19.261092+00
15	auth	0010_alter_group_name_max_length	2025-10-04 06:16:20.06545+00
16	auth	0011_update_proxy_permissions	2025-10-04 06:16:20.262913+00
17	auth	0012_alter_user_first_name_max_length	2025-10-04 06:16:20.384732+00
18	bd_models	0001_initial	2025-10-04 06:16:20.534539+00
19	bd_models	0002_move_upload_files	2025-10-04 06:16:21.394905+00
20	bd_models	0003_delete_ball_delete_ballinstance_and_more	2025-10-04 06:16:22.699157+00
21	bd_models	0004_check_aerich_migrations_initial	2025-10-04 06:16:24.079989+00
22	bd_models	0005_alter_ball_short_name	2025-10-04 06:16:24.15848+00
23	bd_models	0006_player_extra_data	2025-10-04 06:16:24.457363+00
24	bd_models	0007_player_trade_cooldown_policy	2025-10-04 06:16:24.93081+00
25	bd_models	0008_alter_ball_options_alter_ballinstance_options_and_more	2025-10-04 06:16:25.130108+00
26	sessions	0001_initial	2025-10-04 06:16:26.547444+00
27	default	0001_initial	2025-10-04 06:16:28.161058+00
28	social_auth	0001_initial	2025-10-04 06:16:28.293757+00
29	default	0002_add_related_name	2025-10-04 06:16:28.436279+00
30	social_auth	0002_add_related_name	2025-10-04 06:16:28.437418+00
31	default	0003_alter_email_max_length	2025-10-04 06:16:28.605766+00
32	social_auth	0003_alter_email_max_length	2025-10-04 06:16:28.606495+00
33	default	0004_auto_20160423_0400	2025-10-04 06:16:28.694993+00
34	social_auth	0004_auto_20160423_0400	2025-10-04 06:16:28.696062+00
35	social_auth	0005_auto_20160727_2333	2025-10-04 06:16:29.07827+00
36	social_django	0006_partial	2025-10-04 06:16:29.577561+00
37	social_django	0007_code_timestamp	2025-10-04 06:16:30.045509+00
38	social_django	0008_partial_timestamp	2025-10-04 06:16:30.952061+00
39	social_django	0009_auto_20191118_0520	2025-10-04 06:16:31.235658+00
40	social_django	0010_uid_db_index	2025-10-04 06:16:31.378189+00
41	social_django	0011_alter_id_fields	2025-10-04 06:16:32.568375+00
42	social_django	0012_usersocialauth_extra_data_new	2025-10-04 06:16:33.732905+00
43	social_django	0013_migrate_extra_data	2025-10-04 06:16:34.000068+00
44	social_django	0014_remove_usersocialauth_extra_data	2025-10-04 06:16:34.242105+00
45	social_django	0015_rename_extra_data_new_usersocialauth_extra_data	2025-10-04 06:16:35.386681+00
46	social_django	0016_alter_usersocialauth_extra_data	2025-10-04 06:16:36.018662+00
47	social_django	0017_usersocialauth_user_social_auth_uid_required	2025-10-04 06:16:36.344905+00
48	social_django	0003_alter_email_max_length	2025-10-04 06:16:36.728925+00
49	social_django	0001_initial	2025-10-04 06:16:36.795478+00
50	social_django	0002_add_related_name	2025-10-04 06:16:36.861934+00
51	social_django	0005_auto_20160727_2333	2025-10-04 06:16:37.179672+00
52	social_django	0004_auto_20160423_0400	2025-10-04 06:16:37.559787+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
souzmzfiy2m954m4u3p4tqybfwu6zepy	.eJxVjjsLwjAUhf9LZilp2jx0s7pYRMXRJeRx01RLC010UPzvRu2g04Vz-b5zHsi2wQyjlSGqCGiBzvywutX6tG3u53HngdfWMHoMm8qXVbM5oBmS6hq9vAYYZWsTkv9nWpkL9O9HGEyrOpn8kE1pyKbCbP29-2UCyb_Bq-ATjonGubBUgxaFw5wDmRNwAlNOudYMilIw4DjXilJMsKMMrOEFI4CFci5JpwUfdadClN3QtP3PxGkNer4AEFlZKQ:1v4vbS:ROjvkFFQ9RxaQvS-Dj9doSp9GfFOiCTXZtoHT5Cgm9U	2025-10-18 06:18:46.093005+00
p148co8da5qvdc7yfocrcmltqqwffpi5	.eJxVjssKwjAQRf8laynJ1Dx0pwiiLlypy5BpJm2wWGiqC8V_N2oXuhq4wzn3PpiPqep6b9PgBmJzdkch6-P61vtO7sV9q3awRLOJpxkcEoQjmzDrrkNjr4l6G31GxH-GrjrT5f1IXRVda7OfijFNxVhYrL53v8gg_Bsal5qMc0AujJdIaMrAtSaYAQXDpZYaUVE5NYo0F-ik5MCDVOQrXSogblwIWTou-KhblwbbdnW8_Ewc17DnC5nVWKc:1v4vo6:FiMKXZR-zsI0zzaOA-V9_YxlxMj3xa8DS8qKz-H96QA	2025-10-18 06:31:50.473026+00
gxebx1eg2cgila3hdox7t5mr9m6n6kkb	.eJxVjssKwjAQRf8laylpah6684UggsvqKkyaia2tLTYRQfHfjdqFrgbucM69D2IrX3S91T5AQDIlq3y7XMBxb5jI17P5wfaT28aLOlzy7elc3smIaLiGUl899rqyEUn_MwNFje374buigkZHPyZD6pOhMFl-724WQfZvKMGXEafM0FRZbtCozFEpkU0YOkW55NIYgdlYCZQ0NcA5ZdRxgbaQmWBIFTgXpcOCj7oBH3TTHav2Z-KwhjxfPONZbA:1v5lsy:arGfhkMlqTHF7wSszZU0a2zY8KChcvOEWzqsr6MGH2E	2025-10-20 14:08:20.995475+00
hkef1gc3e8iud5azug5vzi9wp3oz45ax	.eJxVjssKwjAQRf8laylpaproTnwgqEgRcRkmzcTWFitOfYD470btQlcDdzjn3gdzJeXN2RlqoUU2ZP5O2fa20QtanaY7OhHU19FqsczG96w6zOasxwxc2sJcCM-mdAGJ_zMLeYXH94OavITaBD9GXUpRVxhNvnc9CqD4NxRARcC5sDzWTlq0OvFcKRQDgV5zqaSyNsWkr1NUPLYgJRfcyxRdrpJUINfgfZB2Cz7qGqg1dbMvjz8TuzXs-QLVTVoC:1v64e1:sVqotYmE8FOtsAZL9Brlw0bwK1XSdRzkT9S8Sq-_0ew	2025-10-21 10:10:09.189485+00
iwpxw6e8y6kujblmk7nto1crxzigzil3	.eJxVjssKwjAQRf8laylJah66E90oqGtXIY9JGywNNI0o4r8btQu7GrjDOfc-kQvJxsGpNOoR0BoJPuRbzPX96B2_kEQO7H44Re5C3j_stkELpHQeW5UTDCq4gpB5ZrS9Qv95pGiD7lTxQzWlqZoKq93vnjcFpHNDq1NbcEwNJtIxA0bWHgsBdEXBS8wEE8ZwqJeSg8DEaMYwxZ5xcFbUnAKW2vsinRZ81Z1Oo-piE_q_idMa9HoDZUVZjQ:1v69ZS:rSJBwF1mLc8EFoblISU0kSYbif4fI3uPYkXiVbhe9LM	2025-10-21 15:25:46.825056+00
\.


--
-- Data for Name: economy; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.economy (id, name, icon) FROM stdin;
1	Capitalist	capitalist.png
2	Communist	communist.png
\.


--
-- Data for Name: friendship; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.friendship (id, since, player1_id, player2_id) FROM stdin;
\.


--
-- Data for Name: guildconfig; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.guildconfig (id, guild_id, spawn_channel, enabled, silent) FROM stdin;
1	1422963286411841619	1422963287481647227	t	f
\.


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.player (id, discord_id, donation_policy, privacy_policy, mention_policy, friend_policy, extra_data, trade_cooldown_policy) FROM stdin;
1	1204740024881512509	1	2	1	1	{}	1
2	1189267310997946568	1	2	1	1	{}	1
3	1349432735701139527	1	2	1	1	{}	1
\.


--
-- Data for Name: regime; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.regime (id, name, background) FROM stdin;
1	Democracy	democracy.png
2	Dictatorship	dictatorship.png
3	Union	union.png
4	team	teams_r9RTOFa.png
5	items	items_W1kHhM9.png
6	villans	Untitled_design_zWAOXTh.png
7	base	Untitled_design_1_WmXJw3j.png
\.


--
-- Data for Name: social_auth_association; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.social_auth_association (id, server_url, handle, secret, issued, lifetime, assoc_type) FROM stdin;
\.


--
-- Data for Name: social_auth_code; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.social_auth_code (id, email, code, verified, "timestamp") FROM stdin;
\.


--
-- Data for Name: social_auth_nonce; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.social_auth_nonce (id, server_url, "timestamp", salt) FROM stdin;
\.


--
-- Data for Name: social_auth_partial; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.social_auth_partial (id, token, next_step, backend, "timestamp", data) FROM stdin;
\.


--
-- Data for Name: social_auth_usersocialauth; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.social_auth_usersocialauth (id, provider, uid, user_id, created, modified, extra_data) FROM stdin;
1	discord	1189267310997946568	1	2025-10-04 06:18:38.10882+00	2025-10-07 15:25:45.304721+00	{"expires": 604800, "auth_time": 1759850745, "token_type": "Bearer", "access_token": "MTM5NjM4OTk4Njc1NTk0MDM4Mg.FQ9chdKKY3U8qcU8CUK1PyIbROVlGZ", "refresh_token": "PKxE7KqWuGQ5G5dV3fbvNLAgsh4OaL"}
\.


--
-- Data for Name: special; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.special (id, name, catch_phrase, start_date, end_date, rarity, emoji, background, tradeable, hidden, credits) FROM stdin;
1	Shiny	**✨ It's a shiny countryball! ✨**	\N	\N	0.00048828125	✨	shiny_oLZM1cF.png	t	f	I'm TS
\.


--
-- Data for Name: trade; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.trade (id, date, player1_id, player2_id) FROM stdin;
\.


--
-- Data for Name: tradeobject; Type: TABLE DATA; Schema: public; Owner: ballsdex
--

COPY public.tradeobject (id, ballinstance_id, player_id, trade_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 100, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: ball_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.ball_id_seq', 57, true);


--
-- Name: ballinstance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.ballinstance_id_seq', 24, true);


--
-- Name: blacklistedguild_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.blacklistedguild_id_seq', 1, false);


--
-- Name: blacklistedid_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.blacklistedid_id_seq', 1, false);


--
-- Name: blacklisthistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.blacklisthistory_id_seq', 1, false);


--
-- Name: block_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.block_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 66, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 52, true);


--
-- Name: economy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.economy_id_seq', 2, true);


--
-- Name: friendship_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.friendship_id_seq', 1, false);


--
-- Name: guildconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.guildconfig_id_seq', 1, true);


--
-- Name: player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.player_id_seq', 3, true);


--
-- Name: regime_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.regime_id_seq', 7, true);


--
-- Name: social_auth_association_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.social_auth_association_id_seq', 1, false);


--
-- Name: social_auth_code_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.social_auth_code_id_seq', 1, false);


--
-- Name: social_auth_nonce_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.social_auth_nonce_id_seq', 1, false);


--
-- Name: social_auth_partial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.social_auth_partial_id_seq', 1, false);


--
-- Name: social_auth_usersocialauth_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.social_auth_usersocialauth_id_seq', 1, true);


--
-- Name: special_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.special_id_seq', 1, true);


--
-- Name: trade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.trade_id_seq', 1, false);


--
-- Name: tradeobject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ballsdex
--

SELECT pg_catalog.setval('public.tradeobject_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: ball ball_country_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ball
    ADD CONSTRAINT ball_country_key UNIQUE (country);


--
-- Name: ball ball_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ball
    ADD CONSTRAINT ball_pkey PRIMARY KEY (id);


--
-- Name: ballinstance ballinstance_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_pkey PRIMARY KEY (id);


--
-- Name: ballinstance ballinstance_player_id_id_961b6354_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_player_id_id_961b6354_uniq UNIQUE (player_id, id);


--
-- Name: blacklistedguild blacklistedguild_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.blacklistedguild
    ADD CONSTRAINT blacklistedguild_discord_id_key UNIQUE (discord_id);


--
-- Name: blacklistedguild blacklistedguild_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.blacklistedguild
    ADD CONSTRAINT blacklistedguild_pkey PRIMARY KEY (id);


--
-- Name: blacklistedid blacklistedid_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.blacklistedid
    ADD CONSTRAINT blacklistedid_discord_id_key UNIQUE (discord_id);


--
-- Name: blacklistedid blacklistedid_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.blacklistedid
    ADD CONSTRAINT blacklistedid_pkey PRIMARY KEY (id);


--
-- Name: blacklisthistory blacklisthistory_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.blacklisthistory
    ADD CONSTRAINT blacklisthistory_pkey PRIMARY KEY (id);


--
-- Name: block block_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.block
    ADD CONSTRAINT block_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: economy economy_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.economy
    ADD CONSTRAINT economy_pkey PRIMARY KEY (id);


--
-- Name: friendship friendship_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.friendship
    ADD CONSTRAINT friendship_pkey PRIMARY KEY (id);


--
-- Name: guildconfig guildconfig_guild_id_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.guildconfig
    ADD CONSTRAINT guildconfig_guild_id_key UNIQUE (guild_id);


--
-- Name: guildconfig guildconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.guildconfig
    ADD CONSTRAINT guildconfig_pkey PRIMARY KEY (id);


--
-- Name: player player_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_discord_id_key UNIQUE (discord_id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: regime regime_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.regime
    ADD CONSTRAINT regime_pkey PRIMARY KEY (id);


--
-- Name: social_auth_association social_auth_association_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_association
    ADD CONSTRAINT social_auth_association_pkey PRIMARY KEY (id);


--
-- Name: social_auth_association social_auth_association_server_url_handle_078befa2_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_association
    ADD CONSTRAINT social_auth_association_server_url_handle_078befa2_uniq UNIQUE (server_url, handle);


--
-- Name: social_auth_code social_auth_code_email_code_801b2d02_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_code
    ADD CONSTRAINT social_auth_code_email_code_801b2d02_uniq UNIQUE (email, code);


--
-- Name: social_auth_code social_auth_code_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_code
    ADD CONSTRAINT social_auth_code_pkey PRIMARY KEY (id);


--
-- Name: social_auth_nonce social_auth_nonce_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_nonce
    ADD CONSTRAINT social_auth_nonce_pkey PRIMARY KEY (id);


--
-- Name: social_auth_nonce social_auth_nonce_server_url_timestamp_salt_f6284463_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_nonce
    ADD CONSTRAINT social_auth_nonce_server_url_timestamp_salt_f6284463_uniq UNIQUE (server_url, "timestamp", salt);


--
-- Name: social_auth_partial social_auth_partial_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_partial
    ADD CONSTRAINT social_auth_partial_pkey PRIMARY KEY (id);


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_pkey PRIMARY KEY (id);


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_provider_uid_e6b5e668_uniq; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_provider_uid_e6b5e668_uniq UNIQUE (provider, uid);


--
-- Name: special special_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.special
    ADD CONSTRAINT special_pkey PRIMARY KEY (id);


--
-- Name: trade trade_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.trade
    ADD CONSTRAINT trade_pkey PRIMARY KEY (id);


--
-- Name: tradeobject tradeobject_pkey; Type: CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.tradeobject
    ADD CONSTRAINT tradeobject_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: ball_country_2e76b520_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ball_country_2e76b520_like ON public.ball USING btree (country varchar_pattern_ops);


--
-- Name: ball_economy_id_e2ffacbf; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ball_economy_id_e2ffacbf ON public.ball USING btree (economy_id);


--
-- Name: ball_regime_id_fd6c5dc6; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ball_regime_id_fd6c5dc6 ON public.ball USING btree (regime_id);


--
-- Name: ballinstance_ball_id_0325f9a8; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ballinstance_ball_id_0325f9a8 ON public.ballinstance USING btree (ball_id);


--
-- Name: ballinstance_player_id_4a04cdf8; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ballinstance_player_id_4a04cdf8 ON public.ballinstance USING btree (player_id);


--
-- Name: ballinstance_special_id_bc6930b1; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ballinstance_special_id_bc6930b1 ON public.ballinstance USING btree (special_id);


--
-- Name: ballinstance_trade_player_id_6781600c; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX ballinstance_trade_player_id_6781600c ON public.ballinstance USING btree (trade_player_id);


--
-- Name: block_player1_id_5a4f0aa5; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX block_player1_id_5a4f0aa5 ON public.block USING btree (player1_id);


--
-- Name: block_player2_id_83ba97b5; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX block_player2_id_83ba97b5 ON public.block USING btree (player2_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: friendship_player1_id_dac289fc; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX friendship_player1_id_dac289fc ON public.friendship USING btree (player1_id);


--
-- Name: friendship_player2_id_7988e39f; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX friendship_player2_id_7988e39f ON public.friendship USING btree (player2_id);


--
-- Name: social_auth_code_code_a2393167; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_code_code_a2393167 ON public.social_auth_code USING btree (code);


--
-- Name: social_auth_code_code_a2393167_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_code_code_a2393167_like ON public.social_auth_code USING btree (code varchar_pattern_ops);


--
-- Name: social_auth_code_timestamp_176b341f; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_code_timestamp_176b341f ON public.social_auth_code USING btree ("timestamp");


--
-- Name: social_auth_partial_timestamp_50f2119f; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_partial_timestamp_50f2119f ON public.social_auth_partial USING btree ("timestamp");


--
-- Name: social_auth_partial_token_3017fea3; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_partial_token_3017fea3 ON public.social_auth_partial USING btree (token);


--
-- Name: social_auth_partial_token_3017fea3_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_partial_token_3017fea3_like ON public.social_auth_partial USING btree (token varchar_pattern_ops);


--
-- Name: social_auth_usersocialauth_uid_796e51dc; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_usersocialauth_uid_796e51dc ON public.social_auth_usersocialauth USING btree (uid);


--
-- Name: social_auth_usersocialauth_uid_796e51dc_like; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_usersocialauth_uid_796e51dc_like ON public.social_auth_usersocialauth USING btree (uid varchar_pattern_ops);


--
-- Name: social_auth_usersocialauth_user_id_17d28448; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX social_auth_usersocialauth_user_id_17d28448 ON public.social_auth_usersocialauth USING btree (user_id);


--
-- Name: trade_player1_id_4761b703; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX trade_player1_id_4761b703 ON public.trade USING btree (player1_id);


--
-- Name: trade_player2_id_739ad466; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX trade_player2_id_739ad466 ON public.trade USING btree (player2_id);


--
-- Name: tradeobject_ballinstance_id_f2522b63; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX tradeobject_ballinstance_id_f2522b63 ON public.tradeobject USING btree (ballinstance_id);


--
-- Name: tradeobject_player_id_ba3b263c; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX tradeobject_player_id_ba3b263c ON public.tradeobject USING btree (player_id);


--
-- Name: tradeobject_trade_id_57bea0c5; Type: INDEX; Schema: public; Owner: ballsdex
--

CREATE INDEX tradeobject_trade_id_57bea0c5 ON public.tradeobject USING btree (trade_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ball ball_economy_id_e2ffacbf_fk_economy_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ball
    ADD CONSTRAINT ball_economy_id_e2ffacbf_fk_economy_id FOREIGN KEY (economy_id) REFERENCES public.economy(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ball ball_regime_id_fd6c5dc6_fk_regime_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ball
    ADD CONSTRAINT ball_regime_id_fd6c5dc6_fk_regime_id FOREIGN KEY (regime_id) REFERENCES public.regime(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ballinstance ballinstance_ball_id_0325f9a8_fk_ball_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_ball_id_0325f9a8_fk_ball_id FOREIGN KEY (ball_id) REFERENCES public.ball(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ballinstance ballinstance_player_id_4a04cdf8_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_player_id_4a04cdf8_fk_player_id FOREIGN KEY (player_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ballinstance ballinstance_special_id_bc6930b1_fk_special_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_special_id_bc6930b1_fk_special_id FOREIGN KEY (special_id) REFERENCES public.special(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ballinstance ballinstance_trade_player_id_6781600c_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.ballinstance
    ADD CONSTRAINT ballinstance_trade_player_id_6781600c_fk_player_id FOREIGN KEY (trade_player_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: block block_player1_id_5a4f0aa5_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.block
    ADD CONSTRAINT block_player1_id_5a4f0aa5_fk_player_id FOREIGN KEY (player1_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: block block_player2_id_83ba97b5_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.block
    ADD CONSTRAINT block_player2_id_83ba97b5_fk_player_id FOREIGN KEY (player2_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: friendship friendship_player1_id_dac289fc_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.friendship
    ADD CONSTRAINT friendship_player1_id_dac289fc_fk_player_id FOREIGN KEY (player1_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: friendship friendship_player2_id_7988e39f_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.friendship
    ADD CONSTRAINT friendship_player2_id_7988e39f_fk_player_id FOREIGN KEY (player2_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trade trade_player1_id_4761b703_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.trade
    ADD CONSTRAINT trade_player1_id_4761b703_fk_player_id FOREIGN KEY (player1_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trade trade_player2_id_739ad466_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.trade
    ADD CONSTRAINT trade_player2_id_739ad466_fk_player_id FOREIGN KEY (player2_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tradeobject tradeobject_ballinstance_id_f2522b63_fk_ballinstance_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.tradeobject
    ADD CONSTRAINT tradeobject_ballinstance_id_f2522b63_fk_ballinstance_id FOREIGN KEY (ballinstance_id) REFERENCES public.ballinstance(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tradeobject tradeobject_player_id_ba3b263c_fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.tradeobject
    ADD CONSTRAINT tradeobject_player_id_ba3b263c_fk_player_id FOREIGN KEY (player_id) REFERENCES public.player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tradeobject tradeobject_trade_id_57bea0c5_fk_trade_id; Type: FK CONSTRAINT; Schema: public; Owner: ballsdex
--

ALTER TABLE ONLY public.tradeobject
    ADD CONSTRAINT tradeobject_trade_id_57bea0c5_fk_trade_id FOREIGN KEY (trade_id) REFERENCES public.trade(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 0A1k7e8seUTtgcqj1pjbbecnL5w23tXzdG4MCwzIt1SUqgKpRsxPWkgJA0TLiXQ

